/**
 * Short film scripts written by Kavinkumar, shown in the
 * "From the Writing Desk" section. Each script is modelled as a
 * sequence of screenplay blocks so the modal can render true script
 * formatting. Tanglish (Romanized Tamil) is kept in natural spelling.
 */

export type ScriptBlock =
  | { type: "time"; text: string } // e.g. "2:17 AM."
  | { type: "scene"; text: string } // slugline — "INT. BEDROOM – NIGHT"
  | { type: "action"; text: string } // narrative / action line
  | { type: "dialogue"; character: string; lines: string[] } // name + quoted lines
  | { type: "transition"; text: string } // "CUT TO BLACK."
  | { type: "titlecard"; text: string }; // 'TITLE CARD: "…"'

export interface Story {
  id: string;
  title: string;
  genre: string;
  setting: string;
  logline: string;
  preview: string[];
  blocks: ScriptBlock[];
}

export const stories: Story[] = [
  {
    id: "2-17-am",
    title: "2:17 AM",
    genre: "Psychological Thriller",
    setting: "INT. BEDROOM – NIGHT",
    logline:
      "A screenwriter who kills off his characters gets a 2 a.m. call from one of them.",
    preview: [
      "Small room. Laptop light mattum room la glow aaguthu. Outside heavy rain sound.",
      "“Ennoda ending mattum yen complete pannala…?”",
    ],
    blocks: [
      { type: "scene", text: "INT. BEDROOM – NIGHT" },
      { type: "time", text: "2:17 AM." },
      { type: "action", text: "Small room. Laptop light mattum room la glow aaguthu." },
      { type: "action", text: "Outside heavy rain sound." },
      { type: "action", text: "ARJUN (24) awake. Eyes red." },
      {
        type: "action",
        text: "Table mela: cold coffee, crumpled papers, cigarettes, unfinished screenplay.",
      },
      {
        type: "action",
        text: "Laptop screen la: TITLE: “LAST CALL” / ENDING PENDING…",
      },
      {
        type: "action",
        text: "Arjun type panna try pannuran. Delete. Again type. Delete.",
      },
      { type: "action", text: "Phone vibrate. UNKNOWN NUMBER." },
      {
        type: "action",
        text: "He cuts. Again call. Cuts. Third time. Slow ah attend pannuran.",
      },
      { type: "action", text: "Silence. Static sound. Then… a girl breathing." },
      { type: "dialogue", character: "GIRL (V.O.)", lines: ["“Thoongalaya…?”"] },
      { type: "dialogue", character: "ARJUN", lines: ["“Yaaru neenga?”"] },
      {
        type: "dialogue",
        character: "GIRL (V.O.)",
        lines: ["“Neenga dhaane… ellaarukkum endings ezhuthuveenga…”"],
      },
      { type: "action", text: "Arjun face serious aaguthu." },
      {
        type: "dialogue",
        character: "GIRL (V.O.)",
        lines: ["“En ending mattum yen complete pannala…?”"],
      },
      { type: "action", text: "Arjun freezes." },
      {
        type: "action",
        text: "Laptop screen la character details open la iruku: MEERA — AGE 22 / STATUS: DEAD",
      },
      {
        type: "action",
        text: "Arjun immediate ah close panna try pannuran. Laptop hangs.",
      },
      { type: "action", text: "Rain sound increase." },
      { type: "dialogue", character: "ARJUN", lines: ["“Yaaru nee…?”"] },
      { type: "dialogue", character: "GIRL (V.O.)", lines: ["“Marandhuttiya…?”"] },
      {
        type: "action",
        text: "Flash cuts: a girl laughing, rain road, bike skid, blood on glass, someone crying.",
      },
      { type: "action", text: "BACK TO ROOM. Arjun sweating." },
      { type: "dialogue", character: "ARJUN", lines: ["“No…”"] },
      {
        type: "dialogue",
        character: "GIRL (V.O.)",
        lines: ["“Story nu nenachu… real feelings ah use pannaadha Arjun…”"],
      },
      { type: "action", text: "Tears slowly form." },
      { type: "dialogue", character: "ARJUN", lines: ["“Meera…”"] },
      {
        type: "action",
        text: "Current suddenly OFF. Full darkness. Only phone speaker light.",
      },
      {
        type: "dialogue",
        character: "GIRL (V.O.)",
        lines: ["“Characters ah create panna easy…”"],
      },
      {
        type: "dialogue",
        character: "GIRL (V.O.)",
        lines: ["“Aana… avanga pain oda vaazhradhu kashtam.”"],
      },
      { type: "action", text: "Call disconnected. Dead silence." },
      { type: "action", text: "Phone screen crack. Battery drains. Dark." },
      { type: "action", text: "Laptop automatic ah ON aaguthu." },
      { type: "action", text: "Screen la one line type aaguthu by itself:" },
      {
        type: "dialogue",
        character: "LAPTOP",
        lines: ["“WRITERS DON’T ALWAYS SURVIVE THEIR STORIES.”"],
      },
      { type: "action", text: "Arjun slowly steps back. Fear. Guilt. Breakdown." },
      { type: "transition", text: "CUT TO BLACK." },
      { type: "time", text: "2:18 AM." },
    ],
  },
  {
    id: "availability",
    title: "Availability",
    genre: "Emotional Drama",
    setting: "EXT. SMALL TEA SHOP – NIGHT",
    logline:
      "Some people become part of your routine before they ever become part of your life.",
    preview: [
      "Tea kadai almost close aagura neram. Light rain.",
      "“Sometimes… people become part of our routine before becoming part of our life.”",
    ],
    blocks: [
      { type: "scene", text: "EXT. SMALL TEA SHOP – NIGHT" },
      { type: "action", text: "Light rain." },
      { type: "action", text: "Tea kadai almost close aagura neram." },
      { type: "action", text: "Three plastic chairs." },
      { type: "action", text: "KARTHICK tea kudichittu phone scroll pannuran." },
      { type: "action", text: "ARJUN opposite side silent ah ukkaandhirukan." },
      {
        type: "dialogue",
        character: "KARTHICK",
        lines: ["“Dei… nee innum avala marakkala la?”"],
      },
      { type: "action", text: "Arjun small smile." },
      { type: "dialogue", character: "ARJUN", lines: ["“Love pannala da…”"] },
      { type: "dialogue", character: "ARJUN", lines: ["“Availability ah pazhagitten.”"] },
      { type: "action", text: "Karthick confused." },
      {
        type: "dialogue",
        character: "ARJUN",
        lines: [
          "“Daily morning message… night call… saaptiya… veettukku poyittiya… paathukko…”",
        ],
      },
      {
        type: "dialogue",
        character: "ARJUN",
        lines: ["“Oru aal daily namma life la irundhuttu… suddenly illaama poyitta…”"],
      },
      { type: "action", text: "Silence. Rain sound." },
      { type: "dialogue", character: "ARJUN", lines: ["“Adhu dhaan kashtam.”"] },
      { type: "action", text: "Karthick slow ah phone lock pannuran." },
      { type: "dialogue", character: "KARTHICK", lines: ["“Apram nee sollalaya?”"] },
      { type: "action", text: "Arjun laughs softly." },
      {
        type: "dialogue",
        character: "ARJUN",
        lines: ["“Sonna… friendship um poidumo nu bayam.”"],
      },
      { type: "action", text: "Tea master distant ah vessel wash pannura sound." },
      { type: "action", text: "Few seconds silence." },
      {
        type: "dialogue",
        character: "ARJUN",
        lines: [
          "“Sometimes… people become part of our routine before becoming part of our life.”",
        ],
      },
      { type: "action", text: "Karthick paathuttu irukan." },
      {
        type: "dialogue",
        character: "ARJUN",
        lines: ["“Aana routine dhaan seekiram mudinjidum.”"],
      },
      { type: "action", text: "Suddenly phone vibration." },
      { type: "action", text: "NILA CALLING." },
      { type: "action", text: "Arjun and Karthick both paakuraanga." },
      { type: "action", text: "Arjun attend pannaama paathuttu irukan." },
      { type: "action", text: "Call cut." },
      { type: "action", text: "Immediately one message." },
      {
        type: "dialogue",
        character: "MESSAGE",
        lines: ["“I reached home. Take care.”"],
      },
      { type: "action", text: "Arjun smile pannuran. Eyes little emotional." },
      { type: "action", text: "Phone lock pannittu pocket la vaikkuran." },
      { type: "dialogue", character: "KARTHICK", lines: ["“Call pannalaya?”"] },
      { type: "action", text: "Arjun tea glass ah paakuran. Small smile." },
      { type: "dialogue", character: "ARJUN", lines: ["“Ippo pesuna… marakka mudiyaadhu.”"] },
      { type: "action", text: "Rain slow ah increase aaguthu." },
      { type: "action", text: "Tea kadai light OFF." },
      { type: "transition", text: "CUT TO BLACK." },
    ],
  },
  {
    id: "unmai-pesu",
    title: "Unmai Pesu",
    genre: "Romantic Drama",
    setting: "EXT. TEA KADA – RAINY EVENING",
    logline:
      "A boy who hides behind pretense reconnects with a childhood friend and discovers that the truth he was too afraid to say is the only thing that can bring them closer.",
    preview: [
      "Tea kada bench la ukkandhu, phone la Harini story scroll panra Kavin. Kavin face la smile. Aana eyes la pain.",
      "Aasai ellarum ketpaanga. Aana sila neram, namma solla bayapadura unmai dhaan namma life ah maathum.",
    ],
    blocks: [
      { type: "transition", text: "FADE IN:" },
      { type: "scene", text: "EXT. TEA KADA – RAINY EVENING" },
      { type: "action", text: "Rain softly falling." },
      { type: "action", text: "Road lights wet surface la reflect aagudhu." },
      { type: "action", text: "Tea glass la steam slow ah rise aagudhu." },
      { type: "action", text: "KAVIN bench la ukkandhu phone scroll pannitu irukkuran." },
      { type: "action", text: "Phone screen la HARINI Instagram story. Birthday party. Rich cafe. Friends. Bright lights." },
      { type: "action", text: "Kavin face la small smile. Aana eyes la pain." },
      { type: "action", text: "MADHAN two tea glass eduthu varran." },
      { type: "dialogue", character: "MADHAN", lines: ["Dei... tea cool aagidum. Phone ah appadiye sapduva pola?"] },
      { type: "dialogue", character: "KAVIN", lines: ["Illa da... summa scroll pannitu irukken."] },
      { type: "dialogue", character: "MADHAN", lines: ["Summa scroll panna face ipdi dull ah irukkuma? Yaaru story?"] },
      { type: "action", text: "Madhan phone pakka try pannuran. Kavin immediately lock pannuran." },
      { type: "dialogue", character: "MADHAN", lines: ["Ahaa... Harini dhaana?"] },
      { type: "action", text: "Kavin silent." },
      { type: "dialogue", character: "MADHAN", lines: ["Innum ava story paathu tea kada la tragedy hero madhiri ukkandhuttu irukka?"] },
      { type: "dialogue", character: "KAVIN", lines: ["Tragedy illa da. Ava happy ah irukka nu paathen."] },
      { type: "dialogue", character: "MADHAN", lines: ["Happy ah irukka nu paathiya... illa nee ava life la illa nu feel pannitiya?"] },
      { type: "action", text: "Kavin looks at Madhan. No answer." },
      { type: "dialogue", character: "MADHAN", lines: ["Message pannuda."] },
      { type: "dialogue", character: "KAVIN", lines: ["Enna nu message panna?"] },
      { type: "dialogue", character: "MADHAN", lines: ["Hi Harini, naan Kavin. Simple."] },
      { type: "dialogue", character: "KAVIN", lines: ["Ava remember pannuvaala da?"] },
      { type: "dialogue", character: "MADHAN", lines: ["Nee message panna dhaan theriyum. Nee ipdi tea kada la ukkandhu ava story ku background music podra madhiri feel panna, avalukku epdi theriyum?"] },
      { type: "action", text: "Kavin phone la Harini profile paakuran." },
      { type: "dialogue", character: "KAVIN", lines: ["Ava life vera level da. Naan innum inga dhaan irukken."] },
      { type: "dialogue", character: "MADHAN", lines: ["Seri... avaloda life perusa pochu. Adhukku un life chinnadha aagiducha?"] },
      { type: "action", text: "Kavin silent. Rain sound konjam increase aagudhu." },
      { type: "dialogue", character: "MADHAN", lines: ["Dei, nee ava kitta pesa bayapadala. Nee un kitta nee pesa bayapadura."] },
      { type: "action", text: "Kavin force smile." },
      { type: "dialogue", character: "KAVIN", lines: ["Nee dialogue writer ah aayita da?"] },
      { type: "dialogue", character: "MADHAN", lines: ["Illa. Unna vida konjam honest ah irukken."] },
      { type: "dialogue", character: "MADHAN", lines: ["Message pannuda. Maximum enna aagum? Reply panna maata. Adhukku mela nee ippo already irukkura state dhaan."] },
      { type: "action", text: "Kavin message box open pannuran. He types: Hi Harini... deletes. Again types: Hey, remember me? deletes again. Phone lock." },
      { type: "dialogue", character: "KAVIN", lines: ["Vendam da."] },
      { type: "dialogue", character: "MADHAN", lines: ["Idhu dhaan un problem. Nee life la ellathayum draft la vechittu send panna bayapadura."] },
      { type: "action", text: "Kavin tea kudikkuran. Behind them, one OLD MAN silently Kavin ah observe pannuran." },
      { type: "titlecard", text: "UNMAI PESU" },
      { type: "scene", text: "EXT. TEA KADA – CONTINUOUS" },
      { type: "action", text: "Madhan phone call attend panna side ku poguran. Kavin alone ah irukkuran." },
      { type: "action", text: "Old Man brass cup eduthu Kavin table pakkam varran." },
      { type: "dialogue", character: "OLD MAN", lines: ["Paiya... tea refill venuma?"] },
      { type: "dialogue", character: "KAVIN", lines: ["Illa thatha, podhum."] },
      { type: "action", text: "Old Man cup ah table la veppan." },
      { type: "dialogue", character: "OLD MAN", lines: ["Podhum nu solradhu tea ku dhaan. Manasukku illa pola."] },
      { type: "dialogue", character: "KAVIN", lines: ["Enna thatha?"] },
      { type: "dialogue", character: "OLD MAN", lines: ["Sila per tea kudikka varuvaanga. Sila per nyabagam kudikka varuvaanga."] },
      { type: "action", text: "Kavin uncomfortable ah smile pannuran." },
      { type: "dialogue", character: "KAVIN", lines: ["Neenga romba observe pannuveengala?"] },
      { type: "dialogue", character: "OLD MAN", lines: ["Kada la velai panra aalukku rendu vishayam theriyanum. Tea evlo strong nu... manushan evlo weak nu."] },
      { type: "action", text: "Old Man brass cup ah Kavin pakkam push pannuran." },
      { type: "dialogue", character: "OLD MAN", lines: ["Indha cup la oru tea kudichu paaru."] },
      { type: "dialogue", character: "KAVIN", lines: ["Illa thatha. Already tea kudichen."] },
      { type: "dialogue", character: "OLD MAN", lines: ["Idhu normal tea illa. Idhu aasai tea."] },
      { type: "action", text: "Kavin sirikkuran." },
      { type: "dialogue", character: "KAVIN", lines: ["Aasai tea ah?"] },
      { type: "dialogue", character: "OLD MAN", lines: ["Moondru thadava. Manasula irukkura aasaiya sollu. Nadakkala na tea free. Nadandha na unmai pesanum."] },
      { type: "action", text: "Kavin cup ah eduthu paakuran. Cup old ah irukkum. Inside engraving faint ah irukkum." },
      { type: "action", text: "Madhan thirumbi varran." },
      { type: "dialogue", character: "MADHAN", lines: ["Enna da, thatha unakku special customer service ah?"] },
      { type: "dialogue", character: "KAVIN", lines: ["Moondru aasai fulfill aagumam."] },
      { type: "dialogue", character: "MADHAN", lines: ["Appo first aasai — bill thatha pay pannattum."] },
      { type: "action", text: "Old Man calm ah smile pannuran." },
      { type: "dialogue", character: "OLD MAN", lines: ["Siru aasai ketkaadhe. Manasula irukkura periya bayathoda koodu aasai kekkanum."] },
      { type: "action", text: "Kavin cup la tea kudikkuran." },
      { type: "dialogue", character: "KAVIN", lines: ["Seri thatha... first wish.", "Ava... oru thadava enna nyabagapaduthuna pothum."] },
      { type: "action", text: "Old Man Kavin ah deep ah paakuran." },
      { type: "dialogue", character: "OLD MAN", lines: ["Aasai kettaachu."] },
      { type: "action", text: "Camera cup close-up. Steam spiral madhiri rise aagudhu." },
      { type: "scene", text: "INT. KAVIN ROOM – NIGHT" },
      { type: "action", text: "Kavin bed la lying. Phone la Harini profile open. Old school photo paakuran." },
      { type: "action", text: "He types: Hi Harini. This is Kavin... delete. Phone aside pottu ceiling paakuran." },
      { type: "scene", text: "INT. HARINI ROOM – SAME NIGHT" },
      { type: "action", text: "Harini shelf clean pannitu irukka. Oru old box keezha vizhudhu." },
      { type: "action", text: "Box la school notebooks, friendship band, paper boat, drawing." },
      { type: "action", text: "Drawing backside la child handwriting: Rain Race Champions — Kavin & Harini." },
      { type: "action", text: "Harini slowly sit pannura. Smile." },
      { type: "dialogue", character: "HARINI", lines: ["Kavin..."] },
      { type: "action", text: "Ava paper boat ah gentle ah touch pannura. Phone eduthu Instagram story podura: Some memories don't fade. They just wait." },
      { type: "scene", text: "INT. KAVIN ROOM – NIGHT" },
      { type: "action", text: "Kavin phone buzz. Harini story notification. He opens. Paper boat photo. His handwriting visible. Kavin freeze." },
      { type: "action", text: "Madhan call." },
      { type: "dialogue", character: "KAVIN", lines: ["Dei..."] },
      { type: "dialogue", character: "MADHAN", lines: ["Enna?"] },
      { type: "dialogue", character: "KAVIN", lines: ["Ava story potrukka da."] },
      { type: "dialogue", character: "MADHAN", lines: ["Yaaru?"] },
      { type: "dialogue", character: "KAVIN", lines: ["Harini. Namma school paper boat."] },
      { type: "dialogue", character: "MADHAN", lines: ["Dei... coincidence da."] },
      { type: "dialogue", character: "KAVIN", lines: ["Aana naan inniku dhaan wish ketten."] },
      { type: "dialogue", character: "MADHAN", lines: ["Athu tea kada thatha oda marketing da. Nee over ah feel pannadha."] },
      { type: "action", text: "Kavin phone screen ah paathu irukkuran." },
      { type: "dialogue", character: "KAVIN", lines: ["Ava enna nyabagapaduthirukka da."] },
      { type: "scene", text: "INT. HARINI ROOM – NIGHT" },
      { type: "action", text: "Harini old box la irukkura items paakra. Expensive room. Stylish lights. Aana ava focus full ah old paper boat mela." },
      { type: "action", text: "Her friend call pannura." },
      { type: "dialogue", character: "FRIEND (V.O.)", lines: ["Hey, tomorrow brunch varriya?"] },
      { type: "dialogue", character: "HARINI", lines: ["Maybe. Konjam work irukku."] },
      { type: "dialogue", character: "FRIEND (V.O.)", lines: ["Birthday week la kooda work ah?"] },
      { type: "dialogue", character: "HARINI", lines: ["Illa... just tired."] },
      { type: "action", text: "Call ends. Harini old contact backup open pannura. Kavin School contact irukkum. She hesitates." },
      { type: "dialogue", character: "HARINI", lines: ["Nee innum indha number use pannuriya?"] },
      { type: "action", text: "She keeps phone down. Message send panna bayapadura." },
      { type: "scene", text: "EXT. TEA KADA – NIGHT" },
      { type: "action", text: "Kavin and Madhan tea kada la. Kavin brass cup ah theduran." },
      { type: "dialogue", character: "MADHAN", lines: ["Dei, nee seriously andha cup ah theduriya?"] },
      { type: "dialogue", character: "KAVIN", lines: ["Coincidence nu sollalam. Aana exact ah naan sonna maari nadandhudhu da."] },
      { type: "dialogue", character: "MADHAN", lines: ["Appo second wish la lottery kekku. Enakku share venum."] },
      { type: "action", text: "Old Man same brass cup oda varran." },
      { type: "dialogue", character: "OLD MAN", lines: ["Aasai rendu?"] },
      { type: "action", text: "Kavin shock." },
      { type: "dialogue", character: "KAVIN", lines: ["Thatha... neenga inga dhaan irundheengala?"] },
      { type: "dialogue", character: "OLD MAN", lines: ["Aasai irukkura edathula naan iruppen."] },
      { type: "dialogue", character: "MADHAN", lines: ["Dialogue vera level la irukku thatha."] },
      { type: "action", text: "Old Man tea pour pannuran." },
      { type: "dialogue", character: "OLD MAN", lines: ["Mudhal aasai nyabagam. Rendaam aasai?"] },
      { type: "action", text: "Kavin cup eduthu hesitate pannuran." },
      { type: "dialogue", character: "KAVIN", lines: ["Ava... en kitta pesanum. Oru normal ah. Oru Kavin, epdi irukka? nu."] },
      { type: "dialogue", character: "OLD MAN", lines: ["Aasai kettaachu. Aana pesa chance vandha... nee pesa theriyanum."] },
      { type: "action", text: "Kavin phone buzz. Message: Hi... Kavin? This is Harini. School Harini." },
      { type: "action", text: "Kavin hand tremble aagudhu." },
      { type: "dialogue", character: "MADHAN", lines: ["Enna da?"] },
      { type: "action", text: "Kavin phone show pannuran. Madhan silent." },
      { type: "dialogue", character: "MADHAN", lines: ["Dei..."] },
      { type: "action", text: "Kavin type pannuran. Delete pannuran. Again type pannuran." },
      { type: "dialogue", character: "MADHAN", lines: ["Dei reply pannu! Ava next birth la reply panna sollala."] },
      { type: "action", text: "Kavin finally sends: Hi Harini. Naan dhaan Kavin. Epdi irukka?" },
      { type: "action", text: "Harini reply: Nalla irukken. Nee? So many years. I saw our paper boat today." },
      { type: "action", text: "Kavin old man pakkam paakuran. Old Man illa." },
      { type: "scene", text: "INT. KAVIN ROOM / HARINI ROOM – NIGHT" },
      { type: "action", text: "Split screen feel. Kavin nervous ah walk pannitu phone la pesuran. Harini bed pakkam old paper boat vechuttu pesura." },
      { type: "dialogue", character: "KAVIN", lines: ["Hello..."] },
      { type: "dialogue", character: "HARINI", lines: ["Kavin?"] },
      { type: "dialogue", character: "KAVIN", lines: ["Hmm... naan dhaan."] },
      { type: "action", text: "Small silence." },
      { type: "dialogue", character: "HARINI", lines: ["Voice konjam maariduchu."] },
      { type: "dialogue", character: "KAVIN", lines: ["Un voice same ah dhaan irukku."] },
      { type: "dialogue", character: "HARINI", lines: ["Poi solladha. School la naan romba kathuven."] },
      { type: "dialogue", character: "KAVIN", lines: ["Athu innum irukku nu nenaikkiren."] },
      { type: "action", text: "Both laugh." },
      { type: "dialogue", character: "HARINI", lines: ["Indha paper boat en kitte innum irukkum nu naaney expect pannala."] },
      { type: "dialogue", character: "KAVIN", lines: ["Adha nee throw pannala?"] },
      { type: "dialogue", character: "HARINI", lines: ["Maybe important ah irundhirukkum."] },
      { type: "action", text: "Kavin emotional." },
      { type: "dialogue", character: "KAVIN", lines: ["Namma rain race nyabagam irukka?"] },
      { type: "dialogue", character: "HARINI", lines: ["Of course. Nee every time cheat pannuva."] },
      { type: "dialogue", character: "KAVIN", lines: ["Naan cheat panna maaten. Engineering correct ah pannuvaen."] },
      { type: "dialogue", character: "HARINI", lines: ["Paper boat ku engineering ah?"] },
      { type: "dialogue", character: "KAVIN", lines: ["Appo irundhe naan visionary."] },
      { type: "action", text: "Harini laughs." },
      { type: "dialogue", character: "HARINI", lines: ["Nee ippo enna panra?"] },
      { type: "action", text: "Kavin freeze. Avan hesitate pannuran." },
      { type: "dialogue", character: "KAVIN", lines: ["Naan... content side la irukken. Short films, shoots, konjam freelance."] },
      { type: "dialogue", character: "HARINI", lines: ["Nice. Nee school la irundhe stories solluva. Lunch break la full class ah gather panni ghost story solluva."] },
      { type: "dialogue", character: "KAVIN", lines: ["Adhellam unakku nyabagam irukka?"] },
      { type: "dialogue", character: "HARINI", lines: ["Sila per marandhuduvom. Sila moments mattum marakkave mudiyadhu."] },
      { type: "action", text: "Silence." },
      { type: "dialogue", character: "KAVIN", lines: ["Nee happy ah irukkiya Harini?"] },
      { type: "action", text: "Harini surprised." },
      { type: "dialogue", character: "HARINI", lines: ["Instagram la paatha happy dhaan theriyum la?"] },
      { type: "dialogue", character: "KAVIN", lines: ["Instagram la ellarum happy dhaan."] },
      { type: "action", text: "Harini soft aagura." },
      { type: "dialogue", character: "HARINI", lines: ["Naan okay dhaan. But sometimes... old days miss aagum."] },
      { type: "dialogue", character: "KAVIN", lines: ["Same."] },
      { type: "action", text: "Comfortable silence." },
      { type: "dialogue", character: "HARINI", lines: ["Meet pannalama? Coffee? Or tea? Since paper boat reunion."] },
      { type: "action", text: "Kavin shocked." },
      { type: "dialogue", character: "KAVIN", lines: ["Meet ah?"] },
      { type: "dialogue", character: "HARINI", lines: ["Illa, video call la paper boat race panna mudiyuma?"] },
      { type: "action", text: "Kavin laughs." },
      { type: "dialogue", character: "KAVIN", lines: ["Meet pannalaam."] },
      { type: "dialogue", character: "HARINI", lines: ["Tomorrow evening? 5 pm? Blue Cafe theriyuma?"] },
      { type: "action", text: "Kavin hesitate." },
      { type: "dialogue", character: "KAVIN", lines: ["Theriyum. Varuven."] },
      { type: "action", text: "Call ends. Kavin mirror pakkam paakuran. Smile slowly fade aagudhu." },
      { type: "dialogue", character: "KAVIN", lines: ["Blue Cafe ah..."] },
      { type: "scene", text: "INT. KAVIN ROOM – NEXT DAY" },
      { type: "action", text: "Kavin wardrobe open pannuran. Simple shirts ellam bed mela throw pannuran. Madhan room ku varran." },
      { type: "dialogue", character: "MADHAN", lines: ["Dei, room la cyclone vandhucha?"] },
      { type: "dialogue", character: "KAVIN", lines: ["Dress illa da."] },
      { type: "dialogue", character: "MADHAN", lines: ["Nee dress illa nu sollradhu poi. Confidence illa nu sollu."] },
      { type: "action", text: "Kavin bed la ukkandhu thalai pudichukkuran." },
      { type: "dialogue", character: "KAVIN", lines: ["Blue Cafe la ava friends ellam poguvaanga da. Naan pona... cheap ah theriyuma?"] },
      { type: "dialogue", character: "MADHAN", lines: ["Dei, tea kada la irundha paiyan cafe ku pona cup price dhaan change aagum. Manushan change aaga koodathu."] },
      { type: "dialogue", character: "KAVIN", lines: ["Unakku easy ah sollalaam. Ava life paatha... naan romba normal ah theriyuren da."] },
      { type: "dialogue", character: "MADHAN", lines: ["Normal ah irukkaradhu thappu illa. Fake ah irukkaradhu dhaan problem."] },
      { type: "dialogue", character: "KAVIN", lines: ["Ava enna paathu disappoint aana?"] },
      { type: "dialogue", character: "MADHAN", lines: ["Nee unmai ah pona, disappoint aana avaloda problem. Nee fake ah pona, adhu un problem."] },
      { type: "action", text: "Kavin silence." },
      { type: "scene", text: "EXT. TEA KADA – NIGHT" },
      { type: "action", text: "Kavin alone tea kada ku varran. Rain stopped. Road wet. Old Man cup clean pannitu irukkar." },
      { type: "dialogue", character: "OLD MAN", lines: ["Moonraam aasai."] },
      { type: "dialogue", character: "KAVIN", lines: ["Enakku theriyala thatha."] },
      { type: "dialogue", character: "OLD MAN", lines: ["Theriyadha aasai kekkaadhe."] },
      { type: "dialogue", character: "KAVIN", lines: ["Naalaiku avala meet panna poren."] },
      { type: "dialogue", character: "OLD MAN", lines: ["Adhula aasai enna?"] },
      { type: "dialogue", character: "KAVIN", lines: ["Ava munnaadi naan... nalla theriyanum."] },
      { type: "dialogue", character: "OLD MAN", lines: ["Nalla ah? Illa vera yaaravo maari ah?"] },
      { type: "action", text: "Kavin looks down." },
      { type: "dialogue", character: "KAVIN", lines: ["Ava level ku theriyanum. Confident ah. Successful ah. Ava paatha Kavin maaritaan nu feel panna vendum."] },
      { type: "action", text: "Old Man serious aaguvaar." },
      { type: "dialogue", character: "OLD MAN", lines: ["Maarina manushan ah paathu sila per sandhoshapaduvaanga. Aana marainja manushan ah paathu yaarum connect aaga maataanga."] },
      { type: "dialogue", character: "KAVIN", lines: ["Naan ipdiye pona ava respect pannuvaala?"] },
      { type: "dialogue", character: "OLD MAN", lines: ["Unmaiya respect panna theriyadha aalukku nee poi build panna respect evlo naal?"] },
      { type: "action", text: "Kavin frustrated." },
      { type: "dialogue", character: "KAVIN", lines: ["Enakku advice venam thatha. Wish dhaan venum."] },
      { type: "action", text: "Old Man silence. Cup la tea pour pannuvaar. Cup la small crack sound." },
      { type: "dialogue", character: "OLD MAN", lines: ["Moonraam aasai thappu na... adhu nadandhaalum tholvi dhaan."] },
      { type: "action", text: "Kavin tea kudikkuran." },
      { type: "dialogue", character: "KAVIN", lines: ["Naalaiku avaloda munnaadi naan perfect ah theriyanum."] },
      { type: "action", text: "Thunder. Cup crack visible." },
      { type: "dialogue", character: "OLD MAN", lines: ["Perfect nu nadikka aarambicha... unmai dhaan mudhal la pogum."] },
      { type: "scene", text: "INT. BLUE CAFE – EVENING" },
      { type: "action", text: "Harini already sitting. Simple but elegant. Nervous but happy." },
      { type: "action", text: "Door opens. Kavin enters. Borrowed stylish shirt. Konjam over-polished. Avan natural ah illa." },
      { type: "dialogue", character: "HARINI", lines: ["Kavin?"] },
      { type: "dialogue", character: "KAVIN", lines: ["Hey Harini! Long time, ya."] },
      { type: "action", text: "Harini slight pause." },
      { type: "dialogue", character: "HARINI", lines: ["Long time."] },
      { type: "action", text: "They sit." },
      { type: "dialogue", character: "HARINI", lines: ["Nee romba... different ah irukka."] },
      { type: "dialogue", character: "KAVIN", lines: ["Yeah, life changed. Work, clients, travel... romba busy."] },
      { type: "dialogue", character: "HARINI", lines: ["Oh. Nice."] },
      { type: "action", text: "Waiter varran." },
      { type: "dialogue", character: "WAITER", lines: ["Sir, order?"] },
      { type: "action", text: "Kavin menu price paathu shock, but hide pannuran." },
      { type: "dialogue", character: "KAVIN", lines: ["One cappuccino. And for you?"] },
      { type: "dialogue", character: "HARINI", lines: ["Tea irukka?"] },
      { type: "dialogue", character: "WAITER", lines: ["Irukku maam."] },
      { type: "dialogue", character: "HARINI", lines: ["One tea."] },
      { type: "action", text: "Kavin surprised." },
      { type: "dialogue", character: "HARINI", lines: ["Enna? Paper boat reunion ku tea dhaan correct la?"] },
      { type: "dialogue", character: "KAVIN", lines: ["Yeah, yeah. But coffee better here."] },
      { type: "action", text: "Harini observe pannura." },
      { type: "dialogue", character: "HARINI", lines: ["Nee innum stories eludhuriya?"] },
      { type: "dialogue", character: "KAVIN", lines: ["Yeah, big plans. Film industry la few people kooda connect aagitu irukken. Big project soon."] },
      { type: "dialogue", character: "HARINI", lines: ["Super. But nee school la solluva stories la oru innocence irukkum. Innum appadiye irukka?"] },
      { type: "dialogue", character: "KAVIN", lines: ["Innocence ellam ippo work aagala Harini. Practical ah irukkanum."] },
      { type: "action", text: "Harini smile fade aagudhu." },
      { type: "dialogue", character: "HARINI", lines: ["Hmm."] },
      { type: "dialogue", character: "KAVIN", lines: ["Nee? I saw your Insta. Great lifestyle. Parties, cafes, brands... super ah irukka."] },
      { type: "dialogue", character: "HARINI", lines: ["Adhu ellam photos dhaan Kavin."] },
      { type: "dialogue", character: "KAVIN", lines: ["But still, vera level."] },
      { type: "dialogue", character: "HARINI", lines: ["Nee enna paaka vandhiya... illa en Instagram ah paaka vandhiya?"] },
      { type: "action", text: "Kavin stuck." },
      { type: "dialogue", character: "KAVIN", lines: ["Illa, naan just..."] },
      { type: "dialogue", character: "HARINI", lines: ["Yesterday phone la pesuna Kavin different ah irundhaan. Ippo en munnaadi ukkandhurukkura Kavin... romba far ah irukkaan."] },
      { type: "dialogue", character: "KAVIN", lines: ["Far ah?"] },
      { type: "dialogue", character: "HARINI", lines: ["Nee romba maarita Kavin."] },
      { type: "action", text: "Kavin nervous smile." },
      { type: "dialogue", character: "KAVIN", lines: ["Better ah?"] },
      { type: "action", text: "Harini straight ah paakra." },
      { type: "dialogue", character: "HARINI", lines: ["Illa. Far ah."] },
      { type: "action", text: "Silence." },
      { type: "dialogue", character: "HARINI", lines: ["Naan childhood friend ah meet panna vandhen. Resume paaka illa."] },
      { type: "action", text: "Kavin hurt." },
      { type: "dialogue", character: "KAVIN", lines: ["Harini..."] },
      { type: "dialogue", character: "HARINI", lines: ["Take care, Kavin."] },
      { type: "action", text: "Harini leaves. Kavin alone. Tea untouched. Cappuccino foam dissolve aagudhu. Kavin slowly sunglasses remove pannuran." },
      { type: "scene", text: "EXT. TEA KADA – NIGHT" },
      { type: "action", text: "Kavin tea kada ku varran. Rain starts again. Madhan already there." },
      { type: "dialogue", character: "MADHAN", lines: ["Meet epdi pochu?"] },
      { type: "action", text: "Kavin silent." },
      { type: "dialogue", character: "MADHAN", lines: ["Dei..."] },
      { type: "dialogue", character: "KAVIN", lines: ["Ava poitta da."] },
      { type: "dialogue", character: "MADHAN", lines: ["Enna pannina?"] },
      { type: "action", text: "Kavin sad laugh." },
      { type: "dialogue", character: "KAVIN", lines: ["Naan illaadha maari nadichen."] },
      { type: "action", text: "Madhan understands." },
      { type: "dialogue", character: "MADHAN", lines: ["Andha third wish ah?"] },
      { type: "action", text: "Kavin nod pannuran. Old Man appears." },
      { type: "dialogue", character: "OLD MAN", lines: ["Perfect ah therinjiduchaa?"] },
      { type: "action", text: "Kavin angry." },
      { type: "dialogue", character: "KAVIN", lines: ["Neenga dhaan sonneenga la aasai nadakkum nu!"] },
      { type: "dialogue", character: "OLD MAN", lines: ["Nadandhudhu. Nee perfect ah therinja. Aana nee theriyala."] },
      { type: "action", text: "Kavin tears." },
      { type: "dialogue", character: "KAVIN", lines: ["Enakku ava lose aagiducha thatha?"] },
      { type: "dialogue", character: "OLD MAN", lines: ["Nee avala lose pannala. Nee unna maraichitta."] },
      { type: "action", text: "Madhan Kavin pakkam ukkaruran." },
      { type: "dialogue", character: "MADHAN", lines: ["Dei... nee lose pannadhu love illa da. Unmai."] },
      { type: "action", text: "Kavin breakdown." },
      { type: "dialogue", character: "KAVIN", lines: ["Naan avala paatha odane bayandhuten da. Avaloda life perusa therinjiduchu. En life... romba chinnadha therinjiduchu."] },
      { type: "dialogue", character: "OLD MAN", lines: ["Un life chinnadha illa pa. Nee adha chinnadha paatha."] },
      { type: "action", text: "Pause." },
      { type: "dialogue", character: "OLD MAN", lines: ["Mudhal aasai — ava enna nyabagapaduthanum.", "Rendaam aasai — ava en kitta pesanum.", "Moonraam aasai — naan vera yaaravo maari theriyanum."] },
      { type: "action", text: "Kavin looks at him." },
      { type: "dialogue", character: "OLD MAN", lines: ["Mudhal rendu aasai la nee avala thedina. Moonraam aasai la nee unna tholaichitta."] },
      { type: "dialogue", character: "KAVIN", lines: ["Ippo enna pannuradhu?"] },
      { type: "action", text: "Old Man cracked cup kuduppan." },
      { type: "dialogue", character: "OLD MAN", lines: ["Aasai mudinjudhu. Ippo unmai pesu."] },
      { type: "scene", text: "EXT. BUS STOP / RAINY ROAD – NIGHT" },
      { type: "action", text: "Kavin Harini ku message pannuran: 5 minutes pesalama? Last time fake ah pesiten. Ippo unmai pesanum." },
      { type: "action", text: "Harini reads. No reply. Kavin bus stop la wait pannuran. Rain drizzle." },
      { type: "action", text: "Harini umbrella oda varra." },
      { type: "dialogue", character: "HARINI", lines: ["5 minutes."] },
      { type: "action", text: "Kavin nod." },
      { type: "dialogue", character: "KAVIN", lines: ["Thanks vandhadhukku."] },
      { type: "dialogue", character: "HARINI", lines: ["Sollu."] },
      { type: "action", text: "Kavin speak panna try pannuran. Stop. Deep breath." },
      { type: "dialogue", character: "KAVIN", lines: ["Cafe la naan pesinadhu... full truth illa."] },
      { type: "dialogue", character: "HARINI", lines: ["Therinjiduchu."] },
      { type: "dialogue", character: "KAVIN", lines: ["Naan unna impress panna try pannala Harini. Naan enna maraikka try panninen."] },
      { type: "action", text: "Harini listens." },
      { type: "dialogue", character: "KAVIN", lines: ["Un Instagram paathen. Un lifestyle paathen. Un friends, places, photos... ellam paathadhum, naan unga world la fit aaga maaten nu bayandhen."] },
      { type: "dialogue", character: "HARINI", lines: ["So nee vera yaaravo maari nadicha?"] },
      { type: "dialogue", character: "KAVIN", lines: ["Aama. Because naan ipdiye vandha... nee disappoint aayiduva nu nenaichen."] },
      { type: "action", text: "Harini hurt but softens." },
      { type: "dialogue", character: "HARINI", lines: ["Kavin, naan unna meet panna vandhadhu nee evlo successful nu paaka illa."] },
      { type: "action", text: "Kavin emotional." },
      { type: "dialogue", character: "KAVIN", lines: ["Enakku theriyum. Aana andha moment la theriyala. Un life perusa pochu nu naan bayandhen. Aana en life chinnadha irukku nu naan dhaan mudivu pannitten."] },
      { type: "action", text: "Harini eyes moist." },
      { type: "dialogue", character: "KAVIN", lines: ["Naan wish ketten... nee enna remember pannanum nu. Aana unmaiya sollanum na... naan dhaan enna naan marandhuten."] },
      { type: "action", text: "Silence. Rain sound." },
      { type: "dialogue", character: "HARINI", lines: ["Naanum un story paatha maari dhaan irukken Kavin."] },
      { type: "action", text: "Kavin confused." },
      { type: "dialogue", character: "HARINI", lines: ["Instagram la naan happy ah theriven. Parties, photos, smiles. Aana sila naal la en kitta real ah pesa yaarum irukka maataanga."] },
      { type: "dialogue", character: "HARINI", lines: ["People like my photos. People like my lifestyle. Aana naan silence ah irundha yaarum notice panna maataanga."] },
      { type: "dialogue", character: "KAVIN", lines: ["Harini..."] },
      { type: "dialogue", character: "HARINI", lines: ["Yesterday phone la pesuna Kavin... enakku familiar ah irundhaan. Cafe la vandha Kavin... enna paathu pesala. Enna impression panna try pannaan."] },
      { type: "action", text: "Kavin nods." },
      { type: "dialogue", character: "KAVIN", lines: ["Sorry."] },
      { type: "dialogue", character: "HARINI", lines: ["Sorry ku mela oru thing venum."] },
      { type: "dialogue", character: "KAVIN", lines: ["Enna?"] },
      { type: "dialogue", character: "HARINI", lines: ["Inime fake ah pesa koodadhu."] },
      { type: "action", text: "Kavin smiles through tears." },
      { type: "dialogue", character: "KAVIN", lines: ["Try pannama iruppen. But bayam vandha?"] },
      { type: "dialogue", character: "HARINI", lines: ["Bayam vandha sollu. Mask podadha."] },
      { type: "action", text: "Small silence. Kavin pocket la irundhu paper eduthu paper boat fold pannuran." },
      { type: "dialogue", character: "HARINI", lines: ["Innum paper boat make panna theriyuma?"] },
      { type: "dialogue", character: "KAVIN", lines: ["Engineering dhaan."] },
      { type: "action", text: "Harini smiles." },
      { type: "dialogue", character: "HARINI", lines: ["Race?"] },
      { type: "dialogue", character: "KAVIN", lines: ["Loser chocolate."] },
      { type: "dialogue", character: "HARINI", lines: ["Ippo chocolate price jasthi."] },
      { type: "dialogue", character: "KAVIN", lines: ["En budget kulla irukkura chocolate dhaan."] },
      { type: "action", text: "Both laugh. Kavin paper boat ah rainwater stream la viduran. Harini kneel panni adha push pannura." },
      { type: "dialogue", character: "KAVIN (V.O.)", lines: ["Sila aasai namma kai seranum nu kaathirukkadhu... namma manasu open aaganum nu dhaan kaathirukkum."] },
      { type: "scene", text: "EXT. TEA KADA – NEXT MORNING" },
      { type: "action", text: "Sunlight. Kavin and Madhan tea kada ku varraanga." },
      { type: "dialogue", character: "MADHAN", lines: ["So... happy ending ah?"] },
      { type: "dialogue", character: "KAVIN", lines: ["Ending illa da. Start maari irukku."] },
      { type: "dialogue", character: "MADHAN", lines: ["Adhaan dangerous. Start dhaan always costly."] },
      { type: "action", text: "Kavin smiles. Old Man ah theduran." },
      { type: "dialogue", character: "KAVIN", lines: ["Anna, inga oru thatha work pannuvaare? White shirt, towel..."] },
      { type: "action", text: "Tea Kada Owner confused." },
      { type: "dialogue", character: "OWNER", lines: ["Yaaru pa?"] },
      { type: "dialogue", character: "KAVIN", lines: ["Rendu naal inga tea kuduthaaru. Brass cup..."] },
      { type: "dialogue", character: "OWNER", lines: ["Inga naanum en paiyanum dhaan pa. Thatha yaarum vela panna maataru."] },
      { type: "action", text: "Kavin and Madhan look at each other." },
      { type: "dialogue", character: "MADHAN", lines: ["Dei... appo bill yaaru collect pannanga?"] },
      { type: "action", text: "Owner still confused. Kavin shelf la brass cup paakuran. Cracked cup. He takes it." },
      { type: "action", text: "Inside engraving clear ah irukkum: Aasai ketka munnaadi... unmai pesu." },
      { type: "action", text: "Kavin smiles. Madhan reads." },
      { type: "dialogue", character: "MADHAN", lines: ["Dei, idha vachu second part pannalaam pola."] },
      { type: "dialogue", character: "KAVIN", lines: ["First part ah life la correct ah panrom. Apram paarpom."] },
      { type: "action", text: "Phone buzz. Harini message: Rain race rematch today?" },
      { type: "action", text: "Kavin replies: Tea kada. 5 pm. No fake Kavin. Harini reply: Good. Real Harini varuven." },
      { type: "action", text: "Kavin smiles." },
      { type: "dialogue", character: "KAVIN (V.O.)", lines: ["Aasai ellarum ketpaanga. Aana sila neram, namakku venum nu ninaikkura vishayam vida... namma solla bayapadura unmai dhaan namma life ah maathum."] },
      { type: "transition", text: "FADE OUT." },
    ],
  },
  {
    id: "last-bench",
    title: "Last Bench",
    genre: "Coming-of-age",
    setting: "INT. COLLEGE CLASSROOM – EVENING",
    logline:
      "On the last day of college, the last bench holds the loudest silence.",
    preview: [
      "College almost empty. Blackboard la: “FAREWELL 2026”. Fans sound mattum.",
      "“Naama ellaarum college ku padikka varom nu nenaippom… Aana sila per… oru life ah theda varuvom.”",
    ],
    blocks: [
      { type: "scene", text: "INT. COLLEGE CLASSROOM – EVENING" },
      { type: "action", text: "College almost empty." },
      {
        type: "action",
        text: "One boy — KAVIN — last bench la ukkaandhu irukan. Classroom silent.",
      },
      { type: "action", text: "Blackboard la: “FAREWELL 2026”" },
      { type: "action", text: "Fans sound mattum." },
      {
        type: "action",
        text: "Avan desk mela oru old attendance paper, few scribbled story ideas, and broken earphones.",
      },
      { type: "action", text: "Door side la light slow ah ulle varudhu." },
      { type: "action", text: "Avan phone open pannuran." },
      {
        type: "action",
        text: "Gallery la: friends laughing, tea kadai selfies, culturals, one blurred photo of a girl, short film practice screenshots.",
      },
      { type: "action", text: "Avan smile pannittu phone off pannuran." },
      { type: "action", text: "Silence." },
      { type: "action", text: "Suddenly corridor la juniors sirichittu odura sound." },
      { type: "action", text: "Avan window vazhiya paakuran." },
      {
        type: "dialogue",
        character: "KAVIN (V.O.)",
        lines: ["“Naama ellaarum college ku padikka varom nu nenaippom…”"],
      },
      {
        type: "dialogue",
        character: "KAVIN (V.O.)",
        lines: ["“Aana sila per… oru life ah theda varuvom.”"],
      },
      { type: "action", text: "He stands." },
      { type: "action", text: "Bag eduthukuran." },
      { type: "action", text: "One last look at the classroom." },
      {
        type: "dialogue",
        character: "KAVIN (V.O.)",
        lines: [
          "“Attendance mudinjidum… Semesters mudinjidum… Aana sila kanavugal…”",
        ],
      },
      { type: "action", text: "He switches off the classroom light." },
      { type: "action", text: "Dark." },
      {
        type: "dialogue",
        character: "KAVIN (V.O.)",
        lines: ["“Last bench la dhaan start aagum.”"],
      },
      { type: "transition", text: "CUT TO BLACK." },
      { type: "titlecard", text: "“Some stories never leave the classroom.”" },
    ],
  },
];
